### ISSUE TITLE
Quicker finalization of transaction in UI

### ISSUE THREAD

**Issue by nounderline** [daimo-eth/daimo#1088]
It might take up to 5 seconds for the app to display a finalized transaction. We want to bring it down to ~2s (2s Base block + network jitter + indexing delay.)

Consider following process diagram of app transaction synchronization:

![Daimo sync drawio (1)](https://github.com/daimo-eth/daimo/assets/765841/42559bfa-656f-403f-a35f-0629d4243ea9)

- We do not consider network conditions, device load, and platform scheduling here.
- We assume transaction is included in next block.
- We assume new block is instantly visible across Base network and there is no indexing delay.

Even with idealized conditions, user may still wait for up to 4s for transaction to appear finalized in the UI. Main reason for this delay is [resync()](https://github.com/daimo-eth/daimo/blob/15044c9b5a4945479d9f021619d09ca0b46ee3f3/apps/daimo-mobile/src/sync/sync.ts#L102) throttling and polling updates (which happens every 1s.)

We can minimize this time by pushing information about new block to an app and requesting a sync immediately when a new block is indexed.

We can further minimize the delay by sending all necessary information about the transaction in an event payload and avoid sync request saving additional network roundtrip. This may save 100-300ms for a mobile user that is physicailly distant from API server (think US-Turkey.)

We could add a server-sent event endpoint that emits a new event when we index it. As we index onchain data to Postgres via Shovel we can either [Shovel integration](https://www.indexsupply.com/shovel/docs/#config-integrations-notification) or use Postgres triggers directly to emit notification that will be consumed via this endpoint.

Another alternative could be push notification but they are more platform-dependent and, in our case, relay on three providers we do not control: Expo and Google/Apple. Since mobile push notifications may be delayed or dropped altogether, I'd avoid push notifications for any in-app information control.

**Comment by dcposch** [comment]
Details from Notion:

### Part 1 - Fast Transactions

One of the most important metrics in Daimo is **transaction speed**. I send a transfer: the transfer shows as pending quickly, then as confirmed in a rollup block several seconds later.

Today, this is too slow. I’ve experienced 5-10 seconds. For this project, we’ll measure this latency and then reduce it as far as possible. The theoretical minimum is 1s average, 2s worst-case driven by Base’s 2-second block time.

We can split userop latency into three parts. Measure all three (before), then reduce as far as possible.

1. **Inclusion latency.** Latency from (signed userop) to (published in a Base block). See `sendUserOpV2`. Can we reduce this by sending our bundle directly to the Base sequencer? Are there any other tricks we can use to optimize this step?
2. **Indexer latency.** Latency from (published in block) to (row in our Postgres DB). We use Shovel to ingest Ethereum events into a database. Does this take significant time? If so, can we accelerate?
3. **Client update latency.** Latency from (row in Postgres) to (app renders confirmed transaction). This is currently slow because the app works by polling `getAccountHistory`. (It does this every 10s+ normally, and every 1s when there’s a pending, unconfirmed operation. So we add at least +500ms on average / 1s worst cast to our total latency here.) Can we push-notify or long-poll instead?

### Bonus - Fast Startup

If we have time after part 1, we can optimize the second-most-important latency in Daimo: startup speed.

As above, we can measure before and after and optimize. I suspect that bundle size and the initial `getAccountHistory` both contribute significantly. It would be very useful to quantify and optimize. I’d like to get startup to reliably under a second.
