### ISSUE TITLE
Navigation improvements

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#396]
Since the current in-app navigation uses a mix of tab bar navigation and native stack navigator inside each tab, there are a number of inconsistencies in different screens.

## Screen Transitions

We have low hanging fruit to improve:

- Make the back and forward buttons actually transition the screen from left to right or right to left
- Make swipe from left edge of screen work everywhere.
- Modals (transfer, device) on Android have a weird transition at the moment.
- On pages like Send or Deposit where there are two tabs at the top, people expect to be able to swipe to switch between them. Make that seamless (also part of the Spatial Navigation)

Example of currently bad screen: setting screen. Clicking the back button takes you to the home tab, but swiping from left edge does nothing, and the transition is jarring rather than smooth.

## Stretch goal: Spatial Tab UI

Snapchat does a great job of nailing this. Other apps like Cash App, Rainbow and Family are also good examples of the spatial navigation we are thinking of: tab bar at the bottom and transitions between screens slide across.

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/6984346/3b838a66-0941-4326-b812-b83cabcbdba5">

**Comment by dcposch** [comment]
## One more stretch goal: no keyboard on tab nav

Currently, clicking the `Send` button on the home screen and tapping the Send tab both do the same thing: they go to the send tab, autofocusing the search bar.

**Ideally, we'd autofocus only when clicking the button.** This allows the user to tab toggle between all five tabs without interruption. (Because once an input is focused, the keyboard hides the tab bar preventing further navigation until blurred.)

**Comment by dcposch** [comment]
done in #434
