### ISSUE TITLE
Link claim error

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#599]
<img src="https://github.com/daimo-eth/daimo/assets/169280/5110ac7f-9f14-468f-aa1e-37ae7cea3f01" width=200 />

> The transaction appears then disappears.
> And there are no transactions on base explorer under my address
> My username: td3

**Comment by nalinbhardwaj** [comment]
- td3 is on an old version, 1.4.5#91: https://ui.honeycomb.io/daimo/environments/prod/datasets/daimo-api/result/mrB3xcy9sWL?tab=events
- dcposch is on new version, 1.4.7#94
- dcposch made link on new contract https://basescan.org/tx/0x3c6b2a2364695913a7f8d8b8fd4f90393a2d70d05127cdaaad37c5b8926ea497
- td3 is on old version and ignored contractAddress, trying to claim it on old contract https://dashboard.tenderly.co/tx/base/0xc67496a32a4118d02ec064bb518c69ab4fb732367edbcd17b0f422cfdbc9423f

Issue with not spacing the back compatibility for new contract well. Fixed by asking td3 to upgrade to latest.
